ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

#[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
#[rule.exported]
#[rule.if-return]
[rule.increment-decrement]
#[rule.var-naming]
[rule.var-declaration]
#[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.struct-tag]
[rule.range-val-in-closure]
[rule.import-shadowing]
[rule.unused-parameter]
[rule.waitgroup-by-value]
[rule.range-val-address]

[rule.line-length-limit]
  arguments = [120]
[rule.function-length]
  arguments =[0,80]
#[rule.cyclomatic]
#  arguments =[10]
